### ISSUE TITLE
When trying to report an error, some undefined functions appear

### ISSUE THREAD

**Issue by a690089735** [JeffHanna/MXSPyCOM#19]
The error message displayed:
-- Error occurred in anonymous codeblock
--  Frame:
--   cs: StringStream:"**	thread data: threadID:17396
**	------------------------------------------------------
**	[stack level: 0]
**	In anonymous codeblock
--		Locals:
--			cs: StringStream:""
--			**getErrorSourceFileOffset**: undefined
--			**getErrorSourceFileLine**: undefined
--		Externals:
--			**getErrorSourceFileName**: Global:**getErrorSourceFileName** : undefined
**	------------------------------------------------------
**	[stack level: 1]
**	called from top-level
"
--   **getErrorSourceFileOffset**: undefined
--   **getErrorSourceFileLine**: undefined
-- Error occurred during fileIn in StringStream:"try(filein(@"e:\\我的坚果云\\max脚本\\vscode_test\\test.ms")) catch(cs = "" as stringStream;stack to:cs;(for i in #("Error;" + " filename: " + (getErrorSourceFileName() as string) + "; position: " + ((getErrorSourceFileOffset() as integer) as string) + "; line: " + ((getErrorSourceFileLine() as integer) as string) + "
" + "callstack: 
" + (cs as string)) + (filterString (getCurrentException()) "
") do setListenerSelText ("
" + i)));setListenerSelText "
""; line number: 1
-- Type error: Call needs function or class, got: undefined
   during OLE automation function call

my maxscript:
```
-- fn do_hello =
-- (
--     print"hello!!"
-- )
-- do_hello()

getnodebyname dem --test error
```

3dmaxver:2014

**Comment by JeffHanna** [comment]
Your script has an error in it. getnodebyname() takes a string as the first argument. You are passing it an undefined variable.
MXSPyCOM.

MXSPyCOM works by reading the user's script as a string and calling execute() on that string. If there are errors in the user's script MaxScript will determine that the error is at the point the "execute()" call is made. It would be extremely difficult, probably impossible, to get the callstack to only show the errors in the user's script, not both it and the wrapper script that runs it.

**Comment by a690089735** [comment]
Yes, I wrote this error on purpose to see what the error message would look like.
What caught my attention was:
**getErrorSourceFileOffset : undefined
getErrorSourceFileLine : undefined
getErrorSourceFileName : global
:getErrorSourceFileName : undefined**
These four functions seem to be trying to parse the error message, but they are not defined.
This looks like a part of mxspycom?

**Comment by a690089735** [comment]
> 您的脚本中有错误。getnodebyname() 将字符串作为第一个参数。您正在向它传递一个未定义的变量。 MXSPyCOM。
> 
> MXSPyCOM 通过将用户脚本作为字符串读取并在该字符串上调用 execute() 来工作。如果用户脚本中有错误，MaxScript 将确定错误出现在“execute()”调用的位置。让调用堆栈只显示用户脚本中的错误，而不是它和运行它的包装脚本，这将是非常困难的，可能是不可能的。

是的，我写这个错误是为了看看错误信息的样子。
引起我注意的是：
getErrorSourceFileOffset : undefined
getErrorSourceFileLine : undefined
getErrorSourceFileName : global
:getErrorSourceFileName : undefined
这四个函数似乎试图解析错误消息，但它们没有定义。
这看起来像是 mxspycom 的一部分？

**Comment by a690089735** [comment]
> Your script has an error in it. getnodebyname() takes a string as the first argument. You are passing it an undefined variable. MXSPyCOM.
> 
> MXSPyCOM works by reading the user's script as a string and calling execute() on that string. If there are errors in the user's script MaxScript will determine that the error is at the point the "execute()" call is made. It would be extremely difficult, probably impossible, to get the callstack to only show the errors in the user's script, not both it and the wrapper script that runs it.


Yes, I wrote this error on purpose, for see what the error message would look like.
What caught my attention was that
**getErrorSourceFileOffset : undefined
getErrorSourceFileLine : undefined
getErrorSourceFileName : undefined**
These three functions seem to try to parse the error message, but they are not defined.
Does this look like part of mxspycom?
@JeffHanna
