### ISSUE TITLE
"The Specified file does not exist on drive" - Pycharm 

### ISSUE THREAD

**Issue by alzariss** [JeffHanna/MXSPyCOM#6]
It appears spaces in file names or in the directory name seem to break the plugin,  tested over several projects with and without spaces and removing the spaces seems to fix the issues.

**Comment by JeffHanna** [comment]
I see the problem. The arguments coming in to MXSPyCOM are separated into a list based on spaces in the string. So a filepath with spaces comes in as multiple arguments. The code is written to only expect a maximum of two arguments, and just takes the last array element as the filepath. So a filename of Test File.py will get truncated to just File.py. 

I should have a fix soon.
